/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * Generated by scripts/generate-skill-icons.ts from content/skills.yaml.
 * To update, edit the mappings in that script and run:
 *   pnpm run generate-skill-icons
 */

export interface SkillIcon {
  /** Path to the icon under /public. */
  src: string;
  /** Representative color of the icon (used for subtle hover accents). */
  color: string;
  /** Whether this is a real brand icon (true) or a generic fallback (false). */
  brand: boolean;
}

export const skillIcons: Record<string, SkillIcon> = {
  Python: {
    src: "/skills/python-original.svg",
    color: "#306998",
    brand: true,
  },
  "C++": {
    src: "/skills/cplusplus-original.svg",
    color: "#00599c",
    brand: true,
  },
  C: {
    src: "/skills/c-original.svg",
    color: "#a9bacd",
    brand: true,
  },
  Rust: {
    src: "/skills/rust.svg",
    color: "#E8EAED",
    brand: true,
  },
  TypeScript: {
    src: "/skills/typescript-original.svg",
    color: "#007acc",
    brand: true,
  },
  Java: {
    src: "/skills/java-original.svg",
    color: "#0074BD",
    brand: true,
  },
  Ada: {
    src: "/skills/ada.svg",
    color: "#E8EAED",
    brand: true,
  },
  "C#": {
    src: "/skills/csharp-original.svg",
    color: "#68217A",
    brand: true,
  },
  Bash: {
    src: "/skills/bash-original.svg",
    color: "#4fa847",
    brand: true,
  },
  SQL: {
    src: "/skills/sql.svg",
    color: "#38BDF8",
    brand: false,
  },
  Matlab: {
    src: "/skills/matlab-original.svg",
    color: "#29d",
    brand: true,
  },
  LaTeX: {
    src: "/skills/latex.svg",
    color: "#008080",
    brand: true,
  },
  PyTorch: {
    src: "/skills/pytorch-original.svg",
    color: "#EE4C2C",
    brand: true,
  },
  "TensorFlow/Keras": {
    src: "/skills/tensorflow-original.svg",
    color: "#ff6f00",
    brand: true,
  },
  NumPy: {
    src: "/skills/numpy-original.svg",
    color: "#4c75cf",
    brand: true,
  },
  Pandas: {
    src: "/skills/pandas-original.svg",
    color: "#ffca00",
    brand: true,
  },
  SciPy: {
    src: "/skills/scipy.svg",
    color: "#8CAAE6",
    brand: true,
  },
  "Scikit-learn": {
    src: "/skills/scikitlearn-original.svg",
    color: "#3499cd",
    brand: true,
  },
  Ray: {
    src: "/skills/ray.svg",
    color: "#028CF0",
    brand: true,
  },
  MLFlow: {
    src: "/skills/mlflow.svg",
    color: "#0194E2",
    brand: true,
  },
  LangChain: {
    src: "/skills/langchain.svg",
    color: "#7FC8FF",
    brand: true,
  },
  "Next.js": {
    src: "/skills/nextdotjs.svg",
    color: "#E8EAED",
    brand: true,
  },
  React: {
    src: "/skills/react-original.svg",
    color: "#61DAFB",
    brand: true,
  },
  "Vue.js": {
    src: "/skills/vuejs-original.svg",
    color: "#41b883",
    brand: true,
  },
  FastAPI: {
    src: "/skills/fastapi-original.svg",
    color: "#049688",
    brand: true,
  },
  Flask: {
    src: "/skills/flask.svg",
    color: "#3BABC3",
    brand: true,
  },
  Vite: {
    src: "/skills/vitejs-original.svg",
    color: "#ffa800",
    brand: true,
  },
  "React Three Fiber": {
    src: "/skills/threedotjs.svg",
    color: "#E8EAED",
    brand: true,
  },
  "Three.js": {
    src: "/skills/threedotjs.svg",
    color: "#E8EAED",
    brand: true,
  },
  TailwindCSS: {
    src: "/skills/tailwindcss-original.svg",
    color: "#38bdf8",
    brand: true,
  },
  "Spring Boot": {
    src: "/skills/spring-original.svg",
    color: "#77bc1f",
    brand: true,
  },
  "Git/GitLab/GitHub": {
    src: "/skills/git-original.svg",
    color: "#F34F29",
    brand: true,
  },
  Docker: {
    src: "/skills/docker-original.svg",
    color: "#019BC6",
    brand: true,
  },
  Jenkins: {
    src: "/skills/jenkins-original.svg",
    color: "#ef3d3a",
    brand: true,
  },
  "GDB/PDB": {
    src: "/skills/gnu.svg",
    color: "#E8EAED",
    brand: true,
  },
  Valgrind: {
    src: "/skills/valgrind.svg",
    color: "#38BDF8",
    brand: false,
  },
  Jira: {
    src: "/skills/jira-original.svg",
    color: "#0052cc",
    brand: true,
  },
  "CI/CD Pipelines": {
    src: "/skills/githubactions-original.svg",
    color: "#2088ff",
    brand: true,
  },
  Vercel: {
    src: "/skills/vercel.svg",
    color: "#E8EAED",
    brand: true,
  },
  AWS: {
    src: "/skills/amazonwebservices-original-wordmark.svg",
    color: "#f90",
    brand: true,
  },
  Sentry: {
    src: "/skills/sentry-original.svg",
    color: "#362d59",
    brand: true,
  },
  JTAG: {
    src: "/skills/jtag.svg",
    color: "#38BDF8",
    brand: false,
  },
  PostgreSQL: {
    src: "/skills/postgresql-original.svg",
    color: "#336791",
    brand: true,
  },
  SQLite: {
    src: "/skills/sqlite-original.svg",
    color: "#0b7fcc",
    brand: true,
  },
  SQLAlchemy: {
    src: "/skills/sqlalchemy-original.svg",
    color: "#ca2727",
    brand: true,
  },
  Drizzle: {
    src: "/skills/drizzle.svg",
    color: "#C5F74F",
    brand: true,
  },
  Alembic: {
    src: "/skills/alembic.svg",
    color: "#38BDF8",
    brand: false,
  },
  Redis: {
    src: "/skills/redis-original.svg",
    color: "#7A0C00",
    brand: true,
  },
  Convex: {
    src: "/skills/convex.svg",
    color: "#EE342F",
    brand: true,
  },
  "AWS S3": {
    src: "/skills/aws-s3.svg",
    color: "#FF9900",
    brand: false,
  },
  "Cloudflare R2": {
    src: "/skills/cloudflare-original.svg",
    color: "#F38020",
    brand: true,
  },
  MCP: {
    src: "/skills/modelcontextprotocol.svg",
    color: "#E8EAED",
    brand: true,
  },
  "Claude Code": {
    src: "/skills/claude.svg",
    color: "#D97757",
    brand: true,
  },
  Cursor: {
    src: "/skills/cursor.svg",
    color: "#E8EAED",
    brand: true,
  },
  Codex: {
    src: "/skills/codex.svg",
    color: "#10A37F",
    brand: true,
  },
  OpenCode: {
    src: "/skills/opencode.svg",
    color: "#E8EAED",
    brand: true,
  },
  Augment: {
    src: "/skills/augment.svg",
    color: "#22C55E",
    brand: false,
  },
  Ollama: {
    src: "/skills/ollama.svg",
    color: "#E8EAED",
    brand: true,
  },
  vLLM: {
    src: "/skills/vllm.svg",
    color: "#30A2FF",
    brand: true,
  },
  Linux: {
    src: "/skills/linux-original.svg",
    color: "#B77B00",
    brand: true,
  },
  "Green Hills Integrity": {
    src: "/skills/green-hills-integrity.svg",
    color: "#2E7D32",
    brand: false,
  },
  VxWorks: {
    src: "/skills/vxworks.svg",
    color: "#0093D0",
    brand: false,
  },
  Windows: {
    src: "/skills/windows11-original.svg",
    color: "#0078d4",
    brand: true,
  },
  macOS: {
    src: "/skills/apple.svg",
    color: "#E8EAED",
    brand: true,
  },
  "Deep Reinforcement Learning": {
    src: "/skills/deep-reinforcement-learning.svg",
    color: "#38BDF8",
    brand: false,
  },
  "Natural Language Processing": {
    src: "/skills/natural-language-processing.svg",
    color: "#38BDF8",
    brand: false,
  },
  "Time Series Forecasting": {
    src: "/skills/time-series-forecasting.svg",
    color: "#38BDF8",
    brand: false,
  },
  "Representation Learning": {
    src: "/skills/representation-learning.svg",
    color: "#38BDF8",
    brand: false,
  },
  "LLM Integration": {
    src: "/skills/llm-integration.svg",
    color: "#38BDF8",
    brand: false,
  },
  "Prompt Engineering": {
    src: "/skills/prompt-engineering.svg",
    color: "#38BDF8",
    brand: false,
  },
};

/** Resolve a skill's icon by name, with a safe default. */
export function getSkillIcon(name: string): SkillIcon {
  return (
    skillIcons[name] ?? {
      src: "/skills/box.svg",
      color: "#38BDF8",
      brand: false,
    }
  );
}
