/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is generated by scripts/generate-content.ts
 * from YAML files in the /content directory.
 *
 * To update content, edit the YAML files and run:
 *   pnpm run generate-content
 *
 * Generated at: 2026-01-09T16:34:12.607Z
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const generatedContent: Record<string, any> = {
  "about": {
    "name": "Daniel Boyle",
    "title": "Full-Stack Developer",
    "tagline": "Building the future, one commit at a time",
    "bio": [
      "Passionate software engineer with 6+ years of experience building web applications and scalable systems.",
      "I love creating elegant solutions to complex problems, contributing to open source, and mentoring other developers.",
      "When I'm not coding, you'll find me exploring new technologies, hiking in the mountains, or working on side projects."
    ],
    "avatar": "/images/avatar.png",
    "resumeUrl": "/resume.pdf"
  },
  "experience": [
    {
      "company": "Tech Innovations Inc.",
      "role": "Senior Full-Stack Developer",
      "period": "2022 - Present",
      "location": "San Francisco, CA",
      "description": "Leading development of cloud-native applications and mentoring junior developers.",
      "highlights": [
        "Architected microservices handling 1M+ requests/day",
        "Reduced deployment time by 60% with CI/CD improvements",
        "Led team of 5 developers on flagship product rewrite"
      ],
      "technologies": [
        "TypeScript",
        "React",
        "Node.js",
        "AWS",
        "PostgreSQL",
        "Docker",
        "Kubernetes"
      ]
    },
    {
      "company": "StartupXYZ",
      "role": "Full-Stack Developer",
      "period": "2020 - 2022",
      "location": "Remote",
      "description": "Built and scaled a SaaS platform from 0 to 50,000 users.",
      "highlights": [
        "Implemented real-time collaboration features using WebSockets",
        "Built payment integration handling $500K+ MRR",
        "Optimized database queries reducing load times by 40%"
      ],
      "technologies": [
        "JavaScript",
        "Vue.js",
        "Python",
        "Django",
        "MongoDB",
        "Redis"
      ]
    },
    {
      "company": "Digital Agency Co.",
      "role": "Frontend Developer",
      "period": "2018 - 2020",
      "location": "New York, NY",
      "description": "Developed responsive web applications for enterprise clients.",
      "highlights": [
        "Delivered 20+ client projects on time and within budget",
        "Introduced component library reducing dev time by 30%",
        "Mentored 3 junior developers"
      ],
      "technologies": [
        "React",
        "TypeScript",
        "CSS/SASS",
        "Node.js",
        "GraphQL"
      ]
    }
  ],
  "skills": [
    {
      "name": "Languages",
      "icon": "💻",
      "skills": [
        {
          "name": "TypeScript",
          "level": 95,
          "years": 6
        },
        {
          "name": "JavaScript",
          "level": 95,
          "years": 8
        },
        {
          "name": "Python",
          "level": 85,
          "years": 5
        },
        {
          "name": "Rust",
          "level": 70,
          "years": 2
        },
        {
          "name": "Go",
          "level": 65,
          "years": 2
        },
        {
          "name": "SQL",
          "level": 85,
          "years": 6
        }
      ]
    },
    {
      "name": "Frameworks",
      "icon": "🚀",
      "skills": [
        {
          "name": "React",
          "level": 95,
          "years": 6
        },
        {
          "name": "Next.js",
          "level": 95,
          "years": 4
        },
        {
          "name": "Node.js",
          "level": 90,
          "years": 6
        },
        {
          "name": "Express",
          "level": 85,
          "years": 5
        },
        {
          "name": "FastAPI",
          "level": 75,
          "years": 2
        },
        {
          "name": "Tailwind CSS",
          "level": 90,
          "years": 3
        }
      ]
    },
    {
      "name": "Tools & DevOps",
      "icon": "🔧",
      "skills": [
        {
          "name": "Git",
          "level": 95,
          "years": 8
        },
        {
          "name": "Docker",
          "level": 85,
          "years": 4
        },
        {
          "name": "Kubernetes",
          "level": 70,
          "years": 2
        },
        {
          "name": "AWS",
          "level": 80,
          "years": 4
        },
        {
          "name": "CI/CD",
          "level": 85,
          "years": 5
        },
        {
          "name": "Linux",
          "level": 85,
          "years": 8
        }
      ]
    },
    {
      "name": "Databases",
      "icon": "🗄️",
      "skills": [
        {
          "name": "PostgreSQL",
          "level": 90,
          "years": 5
        },
        {
          "name": "MongoDB",
          "level": 80,
          "years": 4
        },
        {
          "name": "Redis",
          "level": 75,
          "years": 3
        },
        {
          "name": "SQLite",
          "level": 85,
          "years": 6
        }
      ]
    }
  ],
  "education": [
    {
      "institution": "University of Technology",
      "degree": "Bachelor of Science",
      "field": "Computer Science",
      "period": "2014 - 2018",
      "location": "San Francisco, CA",
      "gpa": "3.8",
      "highlights": [
        "Dean's List all semesters",
        "Senior capstone: Distributed systems project",
        "Teaching assistant for Data Structures course",
        "Member of ACM student chapter"
      ]
    },
    {
      "institution": "Professional Certifications",
      "degree": "Industry Certifications",
      "field": "Cloud & DevOps",
      "period": "2018 - Present",
      "location": "Online",
      "highlights": [
        "AWS Solutions Architect Associate",
        "Google Cloud Professional Developer",
        "Kubernetes Administrator (CKA)",
        "Terraform Associate"
      ]
    }
  ],
  "hobbies": [
    {
      "name": "Open Source",
      "icon": "🌐",
      "description": "Contributing to open source projects and maintaining my own libraries",
      "level": "Active contributor"
    },
    {
      "name": "Gaming",
      "icon": "🎮",
      "description": "Strategy games, puzzle games, and the occasional indie gem",
      "level": "Casual"
    },
    {
      "name": "Reading",
      "icon": "📚",
      "description": "Tech books, sci-fi novels, and software architecture papers",
      "level": "Avid reader"
    },
    {
      "name": "Hiking",
      "icon": "🥾",
      "description": "Exploring trails and enjoying nature",
      "level": "Weekend warrior"
    },
    {
      "name": "Photography",
      "icon": "📷",
      "description": "Capturing landscapes and urban scenes",
      "level": "Hobbyist"
    },
    {
      "name": "Music",
      "icon": "🎵",
      "description": "Playing guitar and exploring new genres",
      "level": "Learning"
    }
  ],
  "contact": {
    "email": "dan.boyle7@gmail.com",
    "github": "github.com/danboyle7",
    "linkedin": "linkedin.com/in/daniel-w-boyle",
    "twitter": "twitter.com/danboyle7",
    "website": "daniel-boyle.com",
    "location": "Elizabeth City, NC",
    "availability": "Open to opportunities"
  },
  "blog": [
    {
      "slug": "building-terminal-portfolio",
      "title": "Building a Terminal-Style Portfolio with Next.js",
      "date": "2024-01-15",
      "excerpt": "How I created this unique terminal-inspired portfolio website using Next.js and TypeScript.",
      "readTime": "8 min read",
      "tags": [
        "Next.js",
        "TypeScript",
        "Portfolio",
        "Creative",
        "React"
      ],
      "content": "# Building a Terminal-Style Portfolio\n\nWhen I set out to create my portfolio, I wanted something that would stand out \nand showcase my personality as a developer. What better way than to build an \ninteractive terminal experience?\n\n## The Concept\n\nThe idea was simple: create a portfolio that feels like a real terminal, complete \nwith a boot sequence, file system navigation, and easter eggs for the curious.\n\n## Technical Implementation\n\nThe portfolio is built with:\n- **Next.js 16** for the framework\n- **TypeScript** for type safety\n- **Tailwind CSS** for styling\n- **React hooks** for state management\n\n## Key Features\n\n1. **Boot Sequence** - A dramatic initialization that sets the mood\n2. **Virtual File System** - Navigate through my experience like files\n3. **Real Commands** - ls, cd, cat, and more actually work\n4. **Easter Eggs** - Try `cowsay`, `matrix`, or `sudo rm -rf /`\n\n## Lessons Learned\n\nBuilding this taught me a lot about:\n- Creating immersive user experiences\n- Balancing creativity with usability\n- The importance of small details\n\nThe terminal aesthetic isn't just a gimmick—it's a statement about who I am as \na developer: someone who lives in the command line and loves what they do.\n"
    }
  ],
  "projects": [
    {
      "name": "terminal-portfolio",
      "description": "This terminal-style portfolio you're viewing right now!",
      "technologies": [
        "Next.js",
        "TypeScript",
        "Tailwind CSS",
        "React"
      ],
      "status": "production",
      "github": "github.com/danielboyle/terminal-portfolio",
      "live": "danielboyle.dev",
      "stars": 42
    },
    {
      "name": "cloud-sync",
      "description": "Real-time file synchronization service with conflict resolution and cross-platform support",
      "technologies": [
        "Rust",
        "gRPC",
        "PostgreSQL",
        "Redis",
        "Docker"
      ],
      "status": "production",
      "github": "github.com/danielboyle/cloud-sync",
      "stars": 128
    },
    {
      "name": "devtools-extension",
      "description": "Browser extension for debugging React applications with component tree visualization",
      "technologies": [
        "TypeScript",
        "React",
        "Chrome APIs",
        "WebExtensions"
      ],
      "status": "beta",
      "github": "github.com/danielboyle/devtools-extension",
      "stars": 67
    },
    {
      "name": "ml-pipeline",
      "description": "Automated machine learning pipeline for data processing, training, and deployment",
      "technologies": [
        "Python",
        "TensorFlow",
        "Docker",
        "Airflow",
        "MLflow"
      ],
      "status": "development",
      "github": "github.com/danielboyle/ml-pipeline",
      "stars": 34
    },
    {
      "name": "api-gateway",
      "description": "High-performance API gateway with rate limiting, caching, and observability",
      "technologies": [
        "Go",
        "Redis",
        "Prometheus",
        "Kubernetes",
        "gRPC"
      ],
      "status": "production",
      "github": "github.com/danielboyle/api-gateway",
      "stars": 256
    }
  ]
};
