/**
 * Content Generation Script
 *
 * This script reads all YAML files from /content and generates a TypeScript
 * file that can be imported at runtime.
 *
 * YAML files are the SINGLE SOURCE OF TRUTH for all content.
 *
 * Usage: pnpm run generate-content
 */

import fs from "fs";
import path from "path";
import yaml from "js-yaml";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CONTENT_DIR = path.join(__dirname, "../content");
const OUTPUT_FILE = path.join(
  __dirname,
  "../src/lib/terminal/generated-content.ts",
);

interface ContentMap {
  about: unknown;
  experience: unknown;
  skills: unknown;
  education: unknown;
  hobbies: unknown;
  contact: unknown;
  blog: unknown;
  projects: unknown;
}

function loadYamlFile(filePath: string): unknown {
  try {
    const content = fs.readFileSync(filePath, "utf8");
    return yaml.load(content);
  } catch (error) {
    console.error(`Error loading ${filePath}:`, error);
    return null;
  }
}

function loadBlogPosts(): unknown[] {
  const blogDir = path.join(CONTENT_DIR, "blog");
  const posts: unknown[] = [];

  if (!fs.existsSync(blogDir)) {
    console.warn("Blog directory not found");
    return posts;
  }

  const files = fs.readdirSync(blogDir).filter((f) => f.endsWith(".yaml"));

  for (const file of files) {
    const content = loadYamlFile(path.join(blogDir, file));
    if (content) {
      posts.push(content);
    }
  }

  return posts;
}

function main() {
  console.log("Generating content from YAML files...");
  console.log(`Content directory: ${CONTENT_DIR}`);

  const content: ContentMap = {
    about: null,
    experience: null,
    skills: null,
    education: null,
    hobbies: null,
    contact: null,
    blog: null,
    projects: null,
  };

  // Load single-file content
  const singleFiles: (keyof ContentMap)[] = [
    "about",
    "experience",
    "skills",
    "education",
    "hobbies",
    "contact",
    "projects",
  ];

  for (const key of singleFiles) {
    const filePath = path.join(CONTENT_DIR, `${key}.yaml`);
    if (fs.existsSync(filePath)) {
      const data = loadYamlFile(filePath);
      if (data && typeof data === "object") {
        // Some YAML files wrap content in a key (e.g., { experience: [...] })
        // Extract the inner content if it exists
        const dataObj = data as Record<string, unknown>;
        if (dataObj[key] !== undefined) {
          content[key] = dataObj[key];
        } else if (key === "contact" && dataObj.contact !== undefined) {
          content[key] = dataObj.contact;
        } else {
          content[key] = data;
        }
      }
      console.log(`  Loaded: ${key}.yaml`);
    } else {
      console.warn(`  Missing: ${key}.yaml`);
    }
  }

  // Load blog posts from directory
  content.blog = loadBlogPosts();
  console.log(`  Loaded: ${(content.blog as unknown[]).length} blog post(s)`);

  // Generate TypeScript output
  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is generated by scripts/generate-content.ts
 * from YAML files in the /content directory.
 *
 * To update content, edit the YAML files and run:
 *   pnpm run generate-content
 *
 * Generated at: ${new Date().toISOString()}
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const generatedContent: Record<string, any> = ${JSON.stringify(content, null, 2)};
`;

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`\nGenerated: ${OUTPUT_FILE}`);
  console.log("Content generation complete!");
}

main();
